### ISSUE TITLE
Add cell type annotation GUI to ChatGSE platform

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/ChatGSE#3] opened 2023-05-04 22:02 UTC
Here's the repo: https://github.com/biocypher/ChatGSE

**Comment by RM7** [comment] 2023-05-29 14:17
Hey Sebastian,

i tried the chatGSE and i like the idea. So i added it to our project and tried my first experiments with text2term and chatGSE. 

But at the moment the is one problem. We need to add text2term to the poetry enviroment. But the versions of the libaries text2term and chatGSE depend on are different. Because we can not change the libaries of text2term we need to change the libaries of chatGSE. 

Here is the output of my try:

poetry add text2term
Using version ^2.3.2 for text2term

Updating dependencies
Resolving dependencies...

The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
  - scipy requires Python <3.12,>=3.8, so it will not be satisfied for Python >=3.12,<4.0

Because no versions of text2term match >2.3.2,<3.0.0
 and text2term (2.3.2) depends on scipy (1.10.1), text2term (>=2.3.2,<3.0.0) requires scipy (1.10.1).
So, because scipy (1.10.1) requires Python <3.12,>=3.8
 and chatgse depends on text2term (^2.3.2), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties       

    For scipy, a possible solution would be to set the `python` property to ">=3.10,<3.12"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers


Am we allowed to change it and should we try it?

**Comment by RM7** [comment] 2023-06-06 13:39
I found the problem. 
The Problem is that in your pyproject.toml file you have specified the python version ^3.10. This indicates that the version can be between >=3.10 <4.0. But scipy can only work with python versions between >=3.8 <3.12.

For scipy the range is to big and because of this we are getting the error. 
When you specify the version in the .toml file in the range of scipy the error goes away.

So now it is working.

**Comment by slobentanzer** [comment] 2023-06-06 13:41
Good that it's working, but I still don't understand the issue.

> But scipy can only work with python versions between >=3.8 <3.12.
`3.10` is `>=3.8, <3.12`. I don't get it.

**Comment by slobentanzer** [comment] 2023-06-06 13:42
> When you specify the version in the .toml file in the range of scipy the error goes away.

What exactly did you change?

**Comment by slobentanzer** [comment] 2023-06-06 13:56
great. can you file a pull request?

**Comment by RM7** [comment] 2023-06-06 14:09
I pushed it to the [sc2sc](https://github.com/biocypher/sc2cl) repository under the folder ChatGSE-main. It contains a full copy of the ChatGSE Project.

According to the pull request I have to go now. So I will do it later.

**Comment by simonmoedinger** [comment] 2023-06-26 09:52
Hei Sebastian, 
could you give me permisson that I can edit this issue? (e.g. assignees etc.)

**Comment by slobentanzer** [comment] 2023-06-26 09:59
See if it works for you now. I gave the WFT team triage access to the repo.

**Closed** 2023-07-03 14:48 UTC
